### ISSUE TITLE
Se necesita un HowTo

### ISSUE THREAD

**Issue by renich** [hsanjuan/twitter-pinbot#1]
Hola, Héctor,

Sería bueno que agregaras un HowTo mínimo al README de perdida para saber como configurarlo. Está medio ambigua la cosa. 

Gracias!

**Comment by hsanjuan** [comment]
Por suerte, alguien ya lo hizo por mí: https://simpleaswater.com/ipfs-cluster-twitter-pinbot/

**Comment by renich** [comment]
Ah, perfecto! Gracias!
